return {}
--   {
--     "SmiteshP/nvim-navic",
--     opts = function()
--       return {
--         separator = " > ",
--         highlight = true,
--         depth_limit = 0,
--         icons = require("lazyvim.config").icons.kinds,
--         lazy_update_context = true,
--       }
--     end,
--   },
-- }
