return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   opts = function(_, opts)
  --     if type(opts.ensure_installed) == "table" then
  --       vim.list_extend(opts.ensure_installed, { "markdown", "markdown_inline", "r", "rnoweb" })
  --     end
  --   end,
  -- },
  -- {
  --   "neovim/nvim-lspconfig",
  --   opts = {
  --     servers = {
  --       r_language_server = {
  --         root_dir = function(fname)
  --           return require("lspconfig.util").root_pattern("DESCRIPTION", "NAMESPACE", ".Rbuildignore")(fname)
  --             or require("lspconfig.util").find_git_ancestor(fname)
  --             or vim.loop.os_homedir()
  --         end,
  --         flags = { debounce_text_changes = 150 },
  --       },
  --     },
  --   },
  -- },
  -- {
  --   "nvim-neotest/neotest",
  --   optional = true,
  --   dependencies = {
  --     "shunsambongi/neotest-testthat",
  --   },
  --   opts = {
  --     adapters = {
  --       ["neotest-testthat"] = {},
  --     },
  --   },
  -- },
}
